### ISSUE TITLE
undefined reference to `leveldb::WriteBatch::~WriteBatch()'

### ISSUE THREAD

**Issue by ppanther1000** [TRUMPCOIN/TRUMP#1]
Trumpcoin can't be compiled on Debian 7:

src/leveldb.h:23: undefined reference to `leveldb::WriteBatch::WriteBatch()'

Leveldb can't be compiled. Do you have an idea how to fix this?

**Comment by TRUMPCOIN** [comment]
fixed on forum

**Comment by le2Ks** [comment]
> 
> 
> fixed on forum

How to solve it ? what's the forum's link
